### ISSUE TITLE
typo on homepage

### ISSUE THREAD

**Issue by AltriusRS** [BeamMP/Website#1]
you have a typo under the "Sync Quality" header on your landing page

What it says:
"BeamMP updates your vehicle position ~100 per second, allowing for a smooth overall experience."

What it should say:
"BeamMP updates your vehicle position ~100 **times** per second, allowing for a smooth overall experience. "

**Comment by AltriusRS** [comment]
So, it has been around 6 months since I filed this issue, yet the problem persists and other than a few reactions, nothing had been done. I am going to close this issue because it just sits on my timeline and annoys me, hopefully this notification also gives you folks a little bit of a prod to fix it.

**Comment by Starystars67** [comment]
Sorry @AltriusRS it seems that the reactions are by one of the staff members and the other is someone else. I am not sure why this did not get onto my radar but it has now been corrected either way.
My apologies for the delay and lack of response.

**Comment by AltriusRS** [comment]
no problem @Starystars67, Looking back on my coment it makes me look like I'm attention seeking, however I can assure you that was not my intention, I just wanted to send a little notification through to someone to bring it back onto a radar if needed :)  

Thanks again and good luck with the future for the project, I can't wait to use it once I have a better computer!

**Comment by Starystars67** [comment]
No no you are good do not worry. I know what you mean and the time between I would say is more than appropriate :) If you see anything else please do let us know! I promise to be more reactive next time.
