### ISSUE TITLE
Server List nav bar broken on Firefox 84.0.1

### ISSUE THREAD

**Issue by lionkor** [BeamMP/Website#2]
https://beammp.com/servers not displaying properly on **Mozilla Firefox 84.0.1**

![image](https://user-images.githubusercontent.com/29932116/103036675-9abf2480-456a-11eb-9b84-8942fb8f01d6.png)

**Comment by 20dka** [comment]
this also happens on chrome

**Comment by lionkor** [comment]
![image](https://user-images.githubusercontent.com/29932116/115546699-a0711080-a2a5-11eb-9d24-c897361c76f2.png)

Likely can be closed?

**Comment by Starystars67** [comment]
I would think so. There is the plan to do a full rebuild of the whole site soon too.
